### ISSUE TITLE
Decoration support for DrawerPanel 

### ISSUE THREAD

**Issue by yathit** [pstjvn/pstj-closure#11]
Most pstj components, such as HeaderPanel supports declarative construction of UI via HTML elements. But the root element, DrawerPanel does not support decoration pattern. 

Should my app be construct all UI by code? Is there suggested pattern?

**Comment by pstjvn** [comment]
This limitation has been lifter after its recent rework so it supports what you are looking for. The main problem is that you cannot compose the templates using call clauses (because there is no single content point in the component, instead there are two (side panel and main panel)).

It is still possible to construct complex app UI from HTML but it is not the pattern of choice for several reasons:
* you need deep looking into the main component to get to the important components (for example imagine getting to an input buried deep in a form which is in a page which is somewhere in the main panel - you will need to write as much code for this as to construct the whole thing imperatively)
* you cannot easily change UI - changes to the HTML will require changes to the code, the other way around is much cleaner - you only change the code

In general the decoration technique is used to construct the complex components (1) and to render server side (2) initial paints. The second is not used anymore in my projects because we do not use Java anymore and also because with modern browsers we have app cache and recently service worker (before we were sing other techniques to keep the js/html/css close to the client) - so first complete UI paint is less than 1 second - thus it is no longer important to send UI as html string and decorate on top of that, instead everything is rendered from JS. 

If you look at the templates for material element you will see a lot of 'call' clauses - so decoration is important and used, but not in the way to create whole apps with it.

I have also experimented with describing the UI with JSON (much simpler than composing complex HTML) but there was the problem with that the run-time requires all components to be loaded on the client (i.e. tree shaking was not possible and the download was way too big for mobile apps). 

Currently the recommended way is to separate you app into domains, create controller for each domain and create UI there. Extract RPC/data calls into a module and test it separately, auto-generate data structures and use pubsub to communicate between domains when needed.

**Comment by yathit** [comment]
Thanks for good explanation. 

I will also go with domain controller pattern. It is easier to test and read.
